@extends('layouts.app')
@section('title', 'Retur sau produs neconform')
@section('content')
<section class="bg-slate-100 py-16 min-h-screen"><div class="max-w-4xl mx-auto px-6">
<h1 class="text-4xl font-bold text-slate-900">Retur sau produs defect/neconform</h1>
<p class="text-slate-500 mt-2 mb-8">Comanda {{ $order->order_number }}</p>
<form method="POST" action="{{ route('returns.store', $order) }}" enctype="multipart/form-data" class="bg-white rounded-3xl shadow-sm p-6 lg:p-8 space-y-7">@csrf
<fieldset><legend class="font-bold text-xl mb-3">Alege tipul solicitării</legend>
@if(now()->timezone('Europe/Bucharest')->lessThanOrEqualTo($withdrawalDeadline))<label class="block p-4 border rounded-xl mb-3"><input type="radio" name="type" value="withdrawal" @checked(old('type', 'withdrawal') === 'withdrawal')> <strong>Vreau să returnez un produs</strong><br><span class="text-sm text-slate-600">Exercitarea dreptului legal de retragere. Motivul este opțional. Termen: {{ $withdrawalDeadline->format('d.m.Y H:i') }}.</span></label>@endif
<label class="block p-4 border rounded-xl"><input type="radio" name="type" value="nonconformity" @checked(old('type', now()->timezone('Europe/Bucharest')->greaterThan($withdrawalDeadline) ? 'nonconformity' : 'withdrawal') === 'nonconformity')> <strong>Produs defect/neconform</strong><br><span class="text-sm text-slate-600">Reclamație separată, în cadrul garanției legale de conformitate.</span></label></fieldset>
<fieldset><legend class="font-bold text-xl mb-3">Produse și cantități</legend>
@foreach($order->items as $item)<div class="grid grid-cols-[1fr_8rem] gap-4 items-center border-b py-3"><span>{{ $item->product_name }} <small class="text-slate-500">(cumpărate: {{ $item->quantity }})</small></span><input aria-label="Cantitate {{ $item->product_name }}" type="number" name="items[{{ $item->id }}]" min="0" max="{{ $item->quantity }}" value="{{ old('items.'.$item->id, 0) }}" class="rounded-xl border-slate-300"></div>@endforeach
@error('items')<p class="text-red-600 mt-2">{{ $message }}</p>@enderror</fieldset>
<div><label class="font-semibold" for="reason">Motivul returului <span class="font-normal text-slate-500">(opțional)</span></label><select id="reason" name="reason" class="mt-2 w-full rounded-xl border-slate-300"><option value="">Prefer să nu specific</option>@foreach(['Nu îmi place','Nu este ceea ce mă așteptam','Am comandat din greșeală','Nu mi se potrivește','Alt motiv'] as $reason)<option @selected(old('reason') === $reason)>{{ $reason }}</option>@endforeach</select></div>
<div><label class="font-semibold" for="notes">Descrierea problemei <span class="text-slate-500">(obligatorie numai pentru produs defect/neconform)</span></label><textarea id="notes" name="notes" maxlength="2000" rows="5" class="mt-2 w-full rounded-xl border-slate-300">{{ old('notes') }}</textarea></div>
<div><label class="font-semibold" for="photos">Fotografii <span class="font-normal text-slate-500">(opționale, maximum 3, JPG/PNG/WebP, maximum 5 MB fiecare)</span></label><input id="photos" type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple class="block mt-2"><p class="text-sm text-slate-500 mt-1">Fotografiile pot ajuta la soluționarea mai rapidă, dar nu sunt o dovadă obligatorie.</p></div>
@if($order->payment_method !== 'stripe')<div class="bg-slate-50 p-4 rounded-xl"><label class="font-semibold" for="bank_iban">IBAN pentru restituire prin transfer bancar</label><input id="bank_iban" name="bank_iban" value="{{ old('bank_iban') }}" class="mt-2 w-full rounded-xl border-slate-300" maxlength="34"><label class="block mt-3"><input type="checkbox" name="accept_bank_transfer" value="1"> Accept restituirea sumelor prin transfer bancar în contul indicat.</label></div>@endif
<div class="bg-cyan-50 p-4 rounded-xl text-sm text-cyan-900">Pentru simpla răzgândire, clientul suportă costul direct al expedierii la NOVELION S.R.L., Str. Daciei nr. 11, Ploiești, Prahova, 100352. Regula nu se aplică automat produselor defecte/neconforme.</div>
<button class="w-full bg-cyan-600 text-white py-3 rounded-xl font-semibold">Trimite solicitarea</button></form></div></section>
@endsection
